# Generated by Django 6.0 on 2025-12-12 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='employees',
            field=models.ManyToManyField(related_name='projects', to='app.employee'),
        ),
    ]
