# Generated by Django 6.0 on 2025-12-15 15:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_expenseitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenseitem',
            name='quantity',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='age',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(18)]),
        ),
        migrations.AlterField(
            model_name='expenseitem',
            name='VAT',
            field=models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
